### ISSUE TITLE
Problem running example data

### ISSUE THREAD

**Issue by vunguyen1907** [hsigeman/findZX#11] opened 2023-03-28 23:58 UTC
Hi

When trying to run example data, I got error massage as below:

(findZX) jc944397@DB1NML3:/mnt/d/findZX$ snakemake -s workflow/findZX --configfile .test/config.yml --cores 1 -R all --use-conda -k
Workflow defines that rule genome_faidx is eligible for caching between workflows (use the --cache argument to enable this).
Workflow defines that rule bwa_index is eligible for caching between workflows (use the --cache argument to enable this).
Building DAG of jobs...
Creating conda environment https:/github.com/snakemake/snakemake-wrappers/raw/0.74.0/bio/bamtools/filter/environment.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /tmp/tmp3o8113wc.yaml:
usage: mamba [-h] [--version] [--slow SLOW] [--enable-coverage]
             [--coverage-file COVERAGE_FILE] [--format FORMAT] [--no-color]
             [--tags TAGS]
             [specs ...]
mamba: error: unrecognized arguments: --quiet --file /mnt/d/findZX/.snakemake/conda/c80299fd2bd98f2ea9613880bfd1c429.yaml --prefix /mnt/d/findZX/.snakemake/conda/c80299fd2bd98f2ea9613880bfd1c429

  File "/home/jc944397/.local/lib/python3.10/site-packages/snakemake/deployment/conda.py", line 388, in create

How can I fix it?

Thanks,
Vu

**Comment by hsigeman** [comment] 2023-04-03 08:11
Hi Vu, 

My guess is that there is some issue with conda here, not with the pipeline itself. Are you running a recent version of conda, and have you tried updating the software? Did you get any error messages when you created the "findZX" conda environment? 

Since there is an error message relating to mamba, you could try running the pipeline without mamba using this command: 
`snakemake -s workflow/findZX --configfile .test/config.yml --cores 1 -R all --use-conda -k --conda-frontend conda`

Alternatively, did you activate the "findZX" conda environment within another conda environment? If so, you could try deactivating this environment before loading findZX.  

If this doesn't work, it would be helpful if you could send the entire error message as an attachment. 

Hope this helps and let me know how it goes,
Hanna

**Comment by vunguyen1907** [comment] 2023-04-04 13:26
Thanks Hanna,

I think I will get back to this later this month and let you know if it is
solved or not.

Regards,
Vu



ᐧ

**Comment by vunguyen1907** [comment] 2023-04-20 08:58
Hi Hanna,

I tried the command as per your suggestion, but it seemed to run forever, almost some days without finishing. I do not think it will take so long. Do you have any idea why?

Regards,
Vu

![image](https://user-images.githubusercontent.com/79078602/233314698-714026dc-c921-4009-acb9-69dbf36d95b5.png)

**Comment by emistasis** [comment] 2024-02-28 16:40
Hi Hanna & Vu!

I'm currently experiencing a very similar issue to Vu and wanted to follow-up. I'm really excited about the prospect of using findZX for my research, so I'd be immensely grateful for any guidance on how to get it to work. 

For context, I'm currently trying to install findZX locally on my macOS. Firstly, I wasn't able to create a conda environment using the command provided in the README:
`conda create -n findZX -c conda-forge -c bioconda python=3.9.4 snakemake-wrapper-utils=0.2.0 snakemake=6.4.0 mamba=0.15.3`

When I attempted this, I would just get the following error and then the installation seemed to stalled.
`Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done` 

Instead, I used the `environment.yml` file provided in the repository to create a conda environment. This worked and created a conda environment: `conda env create -f environment.yml`

Afterwards, I tried running the example data using the following command `/opt/anaconda3/envs/findZX/bin/snakemake -s workflow/findZX --configfile .test/config.yml --cores 1 -R all --use-conda -k --conda-frontend conda` but received the following message:
<img width="1425" alt="image" src="https://github.com/hsigeman/findZX/assets/63172680/17cdacd6-d37e-463a-88a1-84eecd8969e7">
<img width="1510" alt="image" src="https://github.com/hsigeman/findZX/assets/63172680/2b7d9d04-ff03-4001-a5e3-13319d3aebe7">

I then noticed that Vu had activated their findZX env prior to running snakemake, so I tried that. Again, I got a similar error message:
<img width="1511" alt="image" src="https://github.com/hsigeman/findZX/assets/63172680/ea8b7e3a-534b-404e-8bdf-33bf14176f7e">

I'm not sure if editing the `environment.yml` would be recommended. Also, my conda channel priority set to flexible. Thank you! :-)

**Comment by vunguyen1907** [comment] 2024-02-29 05:15
Hi Emmarie,

Thanks four your email.

After many failures with installing this I quited and went through many
other packages but my data seemed to have issues with phenotype-genotype
missmatching so I could not find anything interesting.
I am on my way to collect more data and may come back to install findZX in
the future.

If you will find a way to overcome this issue. Please let me know.

Kindest regards
Vu

**Comment by hsigeman** [comment] 2024-02-29 15:11
Hi Emmarie and Vu, 

I actually got the same problem now when I tried to install a new findZX conda environment on a macbook with a relatively old version of conda. The solution that worked for me was to remove my old version (I am using Miniconda), and download and install the latest version available for my laptop configuration using the download links and instructions here: https://docs.anaconda.com/free/miniconda/.

After that, creating the findZX conda environment using the instructions in the README file worked without issues. To make sure everything with the findZX-pipeline is working I also removed and downloaded a new version of findZX, and and ran the test dataset without errors. 


**Step 1**: Remove and install a new version of conda (https://docs.anaconda.com/free/miniconda/)

**Step 2**: Create the findZX conda environment and activate
```
conda create -n findZX -c conda-forge -c bioconda python=3.9.4 snakemake-wrapper-utils=0.2.0 snakemake=6.4.0 mamba=0.15.3
conda activate findZX
```

**Step 3**: Download a new version of findZX from github and go to the new directory
```
git clone https://github.com/hsigeman/findZX.git
cd findZX 
```

**Step 4**: Run the test dataset
`snakemake -s workflow/findZX --configfile .test/config.yml --cores 1 -R all --use-conda -k `


Hope this works for you as well! Let me know otherwise and I can have another look. 

Best regards, 
Hanna

**Comment by emistasis** [comment] 2024-02-29 15:48
Updating to the latest version of miniconda resolved the issue! 

Thank you so much Hanna! Your help is greatly appreciated. :-)

Best,
Emmarie

**Comment by hsigeman** [comment] 2024-03-01 07:41
Glad it worked, and hope the pipeline will be of use to your research!

I'm closing this issue now since the suggested fix seems to work and the problem is more related to conda than findZX. Vu, I hope the solution will work for you as well once you have your new data. 

Best regards, 
Hanna

**Closed as completed by hsigeman** 2024-03-01 07:41 UTC

**Comment by vunguyen1907** [comment] 2024-03-01 07:47
Yes. After deleted all remain folders of Miniconda3 and re-installed, It
worked well,

Thanks all
Vu
